name: "MF run"
model:
  class_name: MatrixFactorization
  latent_dimension: 100
  weight_decay: 1.0e-4
datamodule:
  num_workers: 4
  batch_size: 1000
lightning_module:
  class_name: MovieLensMFRecommender
optimizer:
  class_name: Adam
trainer:
  max_epochs: 300
  accelerator: gpu
  devices: [2]
  default_root_dir: local
  check_val_every_n_epoch: 1
  amp_backend: native
  log_every_n_steps: 10
callbacks:
  WandbCheckpointCallback:
    artifact_name: mf
