name: "SVD run"
model:
  class_name: SVDRecommender
  n_components: 10
lightning_module:
  class_name: MovieLensNonGradientRecommender
trainer:
  num_sanity_val_steps: 0
callbacks:
  WandbCheckpointCallback:
    artifact_name: svd
