method: bayes
metric:
  goal: maximize
  name: val_ndcg
parameters:
  model:
    value: dssm_extended
  datasets:
    values:
      - max_features_4096_one_hot_-1
      - max_features_4096_one_hot_10
      - max_features_4096_one_hot_100
      - max_features_4096_one_hot_1000
  num_workers:
    value: 4
  hidden_dimensions:
    values:
      - [256, 128, 64]
      - [256, 256, 128]
      - [256, 256, 128, 64]
  head_dimensions:
    values:
      - []
      - [16]
      - [128]
      - [1024]
      - [1024, 16]
  optimizer:
    value: adam
  lr_scheduler:
    value: lambda
  lr_range:
    values:
      - [1.e-3, 1.e-2]
      - [1.e-2, 1.e-1]
      - [1.e-1, 1.e-0]
