project: Recommending
name: "ALS run"
#stage: test
model:
  name: ALSjit
  epochs: 10
  latent_dimension_size: 200
  regularization_lambda: 100
  confidence_alpha: 10
  lambda_decay: 0.75
datamodule:
  directory: local/ml-100k
lightning_module:
  name: MovieLensNonGradientRecommender
logger:
  name: WandbLogger
  save_dir: local
callbacks:
  WandbWatcher: {}
  RecommendingDataOverviewCallback: {}
  WandbCheckpointCallback:
    artifact_name: als
