name: "Baseline run"
model:
  class_name: PopularRecommender
lightning_module:
  class_name: MovieLensNonGradientRecommender
trainer:
  num_sanity_val_steps: 0
callbacks:
  WandbCheckpointCallback:
    artifact_name: baseline
