project: Recommending
name: "Baseline basic models movielens sweep 2"
method: random
metric:
  goal: maximize
  name: test_ndcg@100.mean
parameters:
  model:
    name:
      values: [RandomRecommender, PopularRecommender]
  datamodule:
    directory: local/ml-100k
  lightning_module:
    name: MovieLensBaselineRecommender
  trainer:
    num_sanity_val_steps: 0
  logger:
    name: WandbLogger
    save_dir: local
sweep_id: tqvvvski
