project: Recommending
name: "BPMF sweep 2"
method: random
metric:
  goal: maximize
  name: test_ndcg@100.mean
parameters:
  model:
    name: BayesianPMF
    n_feature_dimensions:
      min: 5
      max: 50
    burn_in_steps:
      min: 1000
      max: 2000
    keeper_steps:
      min: 100
      max: 500
    predictive_explicit_precision:
      values:
        - 1.0e-2
        - 1.0e-1
        - 1.0
    features_hyper_precision_coefficient:
      values:
        - 1.0e-2
        - 1.0e-1
        - 1.0
  datamodule:
    directory: local/ml-100k
    num_workers: 0
  lightning_module:
    name: MovieLensBPMFRecommender
  logger:
    name: WandbLogger
    save_dir: local
  trainer:
    num_sanity_val_steps: 0
