name: "Catboost run"
model:
  class_name: CatboostRecommenderBase
  cb_params:
#    loss_function: ...
    task_type: GPU
    devices: [0]
lightning_module:
  class_name: MovieLensNonGradientRecommender
trainer:
  num_sanity_val_steps: 0
callbacks:
  CatBoostMetrics: {}
  WandbCheckpointCallback:
    artifact_name: catboost
