name: "Catboost aggregator"
model:
  class_name: CatboostMovieLens100kFeatureAggregatorFromArtifacts
  recommender_artifacts: [svd:latest, my_mf_slim:latest]
  lit_modules: [MovieLensNonGradientRecommender, MovieLensMFRecommender]
  movielens_directory: data/ml-100k
  cb_gpu_fit_n_users_per_batch: 1000
  cb_params:
    task_type: GPU # Catboost GPU training is slightly inferior quality to CPU training.
# CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=4
#    gpu_ram_part: 0.2
#    loss_function: QueryCrossEntropy
#    iterations: 10
#    depth: 3
#    gpu_cat_features_storage: CpuPinnedMemory
lightning_module:
  class_name: MovieLensNonGradientRecommender
trainer:
  num_sanity_val_steps: 0
  max_epochs: -1
callbacks:
  CatBoostMetrics: {}
  WandbCheckpointCallback:
    artifact_name: catboost_aggregator
