project: Recommending
name: "Implicit matrix factorization models movielens sweep 3"
method: random
metric:
  goal: maximize
  name: test_ndcg@100.mean
parameters:
  model:
    name: ImplicitMatrixFactorizationRecommender
    implicit_model:
      values: [AlternatingLeastSquares, BayesianPersonalizedRanking]
    factors:
      min: 100
      max: 300
    learning_rate:
      values:
        - 1.0e-2
        - 1.0e-1
    regularization: 1.0e-2
  datamodule:
    directory: local/ml-100k
  lightning_module:
    name: MovieLensBaselineRecommender
  trainer:
    num_sanity_val_steps: 0
  logger:
    name: WandbLogger
    save_dir: local
