name: "Nearest neighbors run"
model:
  class_name: ImplicitNearestNeighborsRecommender
  implicit_model: BM25Recommender
  num_neighbors: 20
lightning_module:
  class_name: MovieLensNonGradientRecommender
trainer:
  num_sanity_val_steps: 0
callbacks:
  WandbWatcher:
    log_every_n_steps: 50
  WandbCheckpointCallback:
    artifact_name: implicit_nn
