name: "MF run"
model:
  class_name: MatrixFactorization
  latent_dimension: 150
  weight_decay: 1.0e-4
loss:
  class_name: MSEConfidenceLoss
  confidence: 0
datamodule:
  num_workers: 4
lightning_module:
  class_name: MovieLensMFRecommender
optimizer:
  class_name: Adam
trainer:
  max_epochs: 50
  accelerator: gpu
  devices: [3]
  default_root_dir: local
  check_val_every_n_epoch: 5
  amp_backend: native
  log_every_n_steps: 1
callbacks:
  EarlyStopping:
    monitor: val_loss
    mode: min
    min_delta: 0
    patience: 5
  WandbCheckpointCallback:
    artifact_name: mf
