name: "Catboost movielens run"
model:
  class_name: CatboostMovieLens100kFeatureRecommender
  movielens_directory: local/ml-100k
  cb_params:
    task_type: GPU
    devices: [0]
lightning_module:
  class_name: MovieLensNonGradientRecommender
trainer:
  num_sanity_val_steps: 0
callbacks:
  CatBoostMetrics: {}
  WandbCheckpointCallback:
    artifact_name: catboost_movielens
