name: "SLIM run"
model:
  class_name: SLIM
  l2_coefficient: 1.0e-5
  l1_coefficient: 1.0e-6
datamodule:
  num_workers: 4
lightning_module:
  class_name: MovieLensSLIMRecommender
  patience: 5
  min_delta: 1.0e-4
optimizer:
  class_name: Adam
trainer:
  accelerator: gpu
  devices: [4]
  reload_dataloaders_every_n_epochs: 1
  accumulate_grad_batches: 1
  enable_model_summary: false
  limit_val_batches: 0
  log_every_n_steps: 1
  default_root_dir: local
  num_sanity_val_steps: 0
  max_epochs: -1
callbacks:
  WandbCheckpointCallback:
    artifact_name: slim
    save_on_train_epoch_end: False
