name: "SLIM run"
model:
  class_name: SLIM
  l2_coefficient: 1.0e-5
  l1_coefficient: 1.0e-6
datamodule:
  directory: local/ml-25m
  test_proportion: 0.01
  batch_size: 200
  num_workers: 4
lightning_module:
  class_name: MovieLens25mSLIMRecommender
  check_val_every_n_epoch: 1
  patience: 10
  min_delta: 1.0e-2
optimizer:
  class_name: Adam
trainer:
  accelerator: gpu
  devices: [2]
  reload_dataloaders_every_n_epochs: 1
  accumulate_grad_batches: 1
  enable_model_summary: false
  limit_val_batches: 0
  limit_test_batches: 2
  log_every_n_steps: 1
  default_root_dir: local
  num_sanity_val_steps: 0
  max_epochs: -1
callbacks:
  ConvenientCheckpointLogCallback: {}
  WandbCheckpointCallback:
    artifact_name: slim
    save_on_train_epoch_end: False
  RecommendingMetricsCallback:
    k: 10
    every_train_epoch: 0
