project: Recommending
name: "ALS"
method: random
metric:
  goal: maximize
  name: test_ndcg@10.mean
parameters:
  model:
    class_name:
      values: [ALSjit, ALSjitBiased]
    epochs:
      min: 1
      max: 10
    latent_dimension_size:
      min: 50
      max: 150
    lambda_decay:
      min: 0.2
      max: 0.6
    confidence_alpha: 10
    regularization_lambda: 100
  lightning_module:
    class_name: MovieLensNonGradientRecommender
  trainer:
    num_sanity_val_steps: 0
