project: Recommending
name: "ALS"
method: random
metric:
  goal: maximize
  name: test_ndcg@10.mean
parameters:
  model:
    class_name:
      values: [ALSjit, ALSjitBiased]
    epochs:
      min: 1
      max: 5
    latent_dimension_size: 100
    lambda_decay: 0.5
    confidence_alpha: 10
    regularization_lambda: 100
  lightning_module:
    class_name: MovieLensNonGradientRecommender
  trainer:
    num_sanity_val_steps: 0
