project: Recommending
name: "ALS movielens sweep 8"
method: random
metric:
  goal: maximize
  name: test_ndcg@100.mean
parameters:
  model:
    name:
      values: [ALSjit, ALSjitBiased]
    epochs:
      min: 1
      max: 10
    latent_dimension_size:
      min: 50
      max: 150
    lambda_decay:
      min: 0.2
      max: 0.6
    confidence_alpha: 10
    regularization_lambda: 100
  datamodule:
    directory: local/ml-100k
    num_workers: 0
  lightning_module:
    name: MovieLensNonGradientRecommender
  logger:
    name: WandbLogger
    save_dir: local
  trainer:
    num_sanity_val_steps: 0
