project: Recommending
name: "Implicit mf"
method: random
metric:
  goal: maximize
  name: test_ndcg@10.mean
parameters:
  model:
    class_name: ImplicitMatrixFactorizationRecommender
    implicit_model:
      values: [AlternatingLeastSquares, BayesianPersonalizedRanking, LogisticMatrixFactorization]
    factors:
      min: 100
      max: 300
    learning_rate:
      values:
        - 1.0e-2
        - 1.0e-1
    regularization: 1.0e-2
  lightning_module:
    class_name: MovieLensNonGradientRecommender
  trainer:
    num_sanity_val_steps: 0

