project: Recommending
name: "Implicit nn"
method: random
metric:
  goal: maximize
  name: test_ndcg@10.mean
parameters:
  model:
    class_name: ImplicitNearestNeighborsRecommender
    implicit_model:
      values: [BM25Recommender, CosineRecommender, TFIDFRecommender]
    num_neighbors:
      min: 1
      max: 100
  lightning_module:
    class_name: MovieLensNonGradientRecommender
  trainer:
    num_sanity_val_steps: 0
