project: Recommending
name: "MF"
method: random
metric:
  goal: maximize
  name: test_ndcg@10.mean
parameters:
  model:
    class_name:
      values:
        - MatrixFactorization
        - ConstrainedProbabilityMatrixFactorization
    latent_dimension:
      min: 50
      max: 150
    weight_decay:
      values:
        - 1.0e-4
        - 1.0e-3
        - 1.0e-2
  loss:
    class_name: MSEConfidenceLoss
    confidence:
      min: 0
      max: 1
  datamodule:
    num_workers: 4
  lightning_module:
    class_name: MovieLensMFRecommender
  optimizer:
    class_name: Adam
  trainer:
    max_epochs: 20
    accelerator: gpu
    devices: [5]
    default_root_dir: local
    check_val_every_n_epoch: 5
    amp_backend: native
  callbacks:
    WandbWatcher:
      log_every_n_steps: 50
    EarlyStopping:
      monitor: val_loss
      mode: min
      patience: 5
