project: Recommending
name: "My MF"
method: random
metric:
  goal: maximize
  name: test_ndcg@10.mean
parameters:
  model:
    class_name: MyMatrixFactorization
    latent_dimension:
      min: 50
      max: 150
    weight_decay:
      values:
        - 1.0e-7
        - 1.0e-6
        - 1.0e-5
  datamodule:
    num_workers: 4
    batch_size: 1000
  lightning_module:
    class_name: MovieLensMyMFRecommender
  optimizer:
    class_name: Adam
  trainer:
    max_epochs:
      min: 20
      max: 50
    accelerator: gpu
    devices: [3]
    default_root_dir: local
    amp_backend: native
