project: Recommending
name: "My MF"
method: random
metric:
  goal: maximize
  name: test_ndcg@10.mean
parameters:
  model:
    class_name: MyMFConfidenceRecommender
    latent_dimension:
      min: 50
      max: 150
  loss:
    ratings_deviation:
      values:
        - 1.0e-1
        - 1.0e-0
        - 1.0e+1
  datamodule:
    num_workers: 4
    batch_size: 100
  lightning_module:
    class_name: MovieLensMFRecommender
  optimizer:
    class_name: Adam
  trainer:
    max_epochs: 30
    check_val_every_n_epoch: 10
    log_every_n_steps: 1
    accelerator: gpu
    devices: [2]
    default_root_dir: local
    amp_backend: native
