project: Recommending
name: "My MF SLIM"
method: random
metric:
  goal: maximize
  name: test_ndcg@10.mean
parameters:
  model:
    class_name: MFSlimRecommender
    latent_dimension:
      min: 10
      max: 150
    l2_regularization: 0.0
    l1_regularization: 1.0e-6
  loss:
    class_name: MSELoss
  datamodule:
    num_workers: 4
    batch_size: 1000
  lightning_module:
    class_name: MovieLensMFRecommender
  optimizer:
    class_name: Adam
  trainer:
    max_epochs: 500
    check_val_every_n_epoch: 10
    log_every_n_steps: 1
    accelerator: gpu
    devices: [5]
    default_root_dir: local
    amp_backend: native
  callbacks:
    EarlyStopping:
      monitor: val_ndcg@10
      check_on_train_epoch_end: False
      mode: max
