project: Recommending
name: "My MF SLIM"
method: random
metric:
  goal: maximize
  name: test_ndcg@10.mean
parameters:
  model:
    class_name: MyMfSlimConfidenceHybridRecommender
    latent_dimension:
      min: 25
      max: 125
  loss:
    ratings_deviation:
      values:
        - 1.0e-1
        - 1.0e-0
        - 1.0e+1
        - 1.0e+2
  datamodule:
    num_workers: 4
    batch_size: 1000
  lightning_module:
    class_name: MovieLensMyMFRecommender
  optimizer:
    class_name: Adam
  trainer:
    max_epochs: 500
    check_val_every_n_epoch: 10
    log_every_n_steps: 1
    accelerator: gpu
    devices: [2]
    default_root_dir: local
    amp_backend: native
  callbacks:
    EarlyStopping:
      monitor: val_loss
      patience: 20
