project: Recommending
name: "SVD"
method: random
metric:
  goal: maximize
  name: test_ndcg@10.mean
parameters:
  model:
    class_name: UnpopularSVDRecommender
    n_components: 10
    unpopularity_coef:
      values:
        - 0
        - 1.0e-6
        - 1.0e-3
        - 1.0e-1
        - 1.0
  lightning_module:
    class_name: MovieLensNonGradientRecommender
  trainer:
    num_sanity_val_steps: 0
