project: Recommending
name: "SVD"
method: random
metric:
  goal: maximize
  name: test_ndcg@10.mean
parameters:
  model:
    class_name: SVDRecommender
    n_components:
      min: 1
      max: 20
  lightning_module:
    class_name: MovieLensNonGradientRecommender
  trainer:
    num_sanity_val_steps: 0
