project: Recommending
name: "SVD movielens sweep"
method: random
metric:
  goal: maximize
  name: test_ndcg@100.mean
parameters:
  model:
    name: SVDRecommender
    n_components:
      min: 10
      max: 500
  datamodule:
    directory: local/ml-100k
  lightning_module:
    name: MovieLensNonGradientRecommender
  trainer:
    num_sanity_val_steps: 0
  logger:
    name: WandbLogger
    save_dir: local
