project: Recommending
name: "ALS run"
#stage: test
model:
  name: ALSjitBiased
#  epochs: 30
  epochs: 1
  latent_dimension_size: 300
  regularization_lambda: 100
  confidence_alpha: 10
  lambda_decay: 0.75
datamodule:
  directory: local/ml-100k
lightning_module:
  name: MovieLensALSRecommender
logger:
  name: WandbLogger
  save_dir: local
callbacks:
  WandbWatcher: {}
  RecommendingDataOverviewCallback: {}
  WandbCheckpointCallback:
    artifact_name: ALS
#trainer:
#  num_sanity_val_steps: 0
