project: Recommending
name: "ALS movielens sweep 6"
method: random
metric:
  goal: maximize
  name: test_ndcg@100.mean
parameters:
  model:
    name:
      values: [ALSjit, ALSjitBiased]
    epochs:
      min: 5
      max: 20
    latent_dimension_size:
      min: 50
      max: 500
    lambda_decay:
      min: 0.5
      max: 0.9
    confidence_alpha: 10
    regularization_lambda: 100
  datamodule:
    directory: local/ml-100k
    num_workers: 0
  lightning_module:
    name: MovieLensALSRecommender
  logger:
    name: WandbLogger
    save_dir: local
  trainer:
    num_sanity_val_steps: 0
sweep_id: 3xmqqhp9
