project: Recommending
name: "ALS debug run"
model:
  name: ALSJITBiased
  epochs: 10
  latent_dimension_size: 10
  regularization_lambda: 1.0e-2
  confidence_alpha: 40
train_explicit:
  local/train_explicit_debug.npz
