project: Recommending
name: "BPMF run"
stage: test
model:
  name: BayesianPMF
  n_feature_dimensions: 10
  burn_in_steps: 200
  keeper_steps: 300
  predictive_explicit_precision: 1.0e-2
  features_hyper_precision_coefficient: 1.0e-2
datamodule:
  directory: local/ml-100k
  num_workers: 0
lightning_module:
  name: MovieLensNonGradientRecommender
trainer:
  num_sanity_val_steps: 0
logger:
  name: WandbLogger
  save_dir: local
callbacks:
  WandbCheckpointCallback:
    artifact_name: bpmf
