project: Recommending
name: "Constrained PMF sweep"
method: bayes
metric:
  goal: minimize
  name: val_loss
trainer:
  max_epochs: 50
  accelerator: gpu
  default_root_dir: local
  check_val_every_n_epoch: 3
callbacks:
  EarlyStopping:
    monitor: val_loss
    mode: min
    min_delta: 1.0e-2
    patience: 2
  automatic_mixed_precision:
    amp_backend: native
  GradientAccumulationScheduler:
    scheduling: {0: 10}
logger:
  name: WandbLogger
  save_dir: local
parameters:
  model:
    parameters:
      name:
        value: ConstrainedProbabilityMatrixFactorization
      latent_dimension:
        min: 10
        max: 20
      weight_decay:
        min: 1.0e-3
        max: 1.0e-2
  lightning_module:
    parameters:
      name:
        value: LitProbabilityMatrixFactorization
      batch_size:
        value: 1.0e+8
      num_workers:
        value: 4
  optimizer:
    parameters:
      name:
        value: SGD
      learning_rate:
        min: 5.0e-4
        max: 5.0e-3
      momentum:
        min: 0.9
        max: 0.99
  callbacks:
    parameters:
      StochasticWeightAveraging:
        parameters:
          swa_lrs:
            min: 1.0e-3
            max: 1.0e-2
          swa_epoch_start:
            min: 10
            max: 15
          annealing_epochs:
            value: 5
          annealing_strategy:
            value: cos




