project: Recommending
name: "Constrained PMF sweep level 2"
method: bayes
metric:
  goal: minimize
  name: val_loss
parameters:
  model:
    value: constrained_probabilistic_matrix_factorization
  max_epochs:
    value: 50
  batch_size:
    value: 1.0e8
  n_batches_for_gradient_accumulation:
    value: 10
  num_workers:
    value: 4
  check_val_every_n_epoch:
    value: 3
  early_stopping:
    parameters:
      monitor:
        value: val_loss
      mode:
        value: min
      min_delta:
        value: 1.0e-2
      patience:
        value: 3
  automatic_mixed_precision:
    parameters:
      amp_backend:
        value: native
  stochastic_weight_averaging:
    parameters:
      enable:
        value: true
      swa_lrs:
        min: 1.0e-1
        max: 1.0
      swa_epoch_start:
        distribution: q_normal
        mu: 5
        sigma: 2
      annealing_epochs:
        distribution: q_normal
        mu: 3
        sigma: 2
      annealing_strategy:
        value: linear
  latent_dimension:
    distribution: q_normal
    mu: 10
    sigma: 5
  weight_decay:
    min: 1.0e-3
    max: 1.0e-2
  optimizer_kwargs:
    parameters:
      optimizer:
        value: adam
sweep_id: qgs6cb9s
