project: Recommending
name: "Constrained PMF debug run"
model: constrained_probabilistic_matrix_factorization
max_epochs: 50
batch_size: 1.0e+8
n_batches_for_gradient_accumulation: 10
num_workers: 4
check_val_every_n_epoch: 3
early_stopping:
  monitor: val_loss
  mode: min
  min_delta: 1.0e-2
  patience: 3
automatic_mixed_precision:
  amp_backend: native
stochastic_weight_averaging:
  enable: true
  swa_lrs: 1.0e-2
  swa_epoch_start: 10
  annealing_epochs: 5
  annealing_strategy: linear
latent_dimension: 10
weight_decay: 1.0e-3
optimizer_kwargs:
  optimizer: adam
