project: Recommending
name: "Nearest neighbors run"
stage: test
model:
  name: ImplicitNearestNeighborsRecommender
  implicit_model: BM25Recommender
  num_neighbors: 5
datamodule:
  directory: local/ml-100k
lightning_module:
  name: MovieLensBaselineRecommender
trainer:
  num_sanity_val_steps: 0
logger:
  name: WandbLogger
  save_dir: local
callbacks:
  WandbWatcher:
    log_every_n_steps: 50
  WandbCheckpointCallback:
    artifact_name: pmf
