project: Recommending
name: "Nearest neighbors movielens sweep"
method: random
metric:
  goal: maximize
  name: test_ndcg@100.mean
parameters:
  model:
    name: ImplicitRecommender
    implicit_model:
      values: [BM25Recommender, CosineRecommender, TFIDFRecommender]
  datamodule:
    directory: local/ml-100k
  lightning_module:
    name: MovieLensBaselineRecommender
  trainer:
    num_sanity_val_steps: 0
  logger:
    name: WandbLogger
    save_dir: local
sweep_id: lceajjed
