project: Recommending
name: "PMF run"
model:
  name: ProbabilityMatrixFactorization
  latent_dimension: 10
  weight_decay: 1.0e-3
loss:
  name: PersonalizedRankingLoss
datamodule:
  name: PMFDataModule
  directory: local/ml-100k
  batch_size: 100
  num_workers: 0
metrics:
  k: [10, 20]
lightning_module:
  name: LitProbabilityMatrixFactorization
optimizer:
  name: Adam
trainer:
  max_epochs: 50
  accelerator: gpu
  devices: [0]
  default_root_dir: local
  check_val_every_n_epoch: 5
  amp_backend: native
  log_every_n_steps: 1
callbacks:
  EarlyStopping:
    monitor: val_loss
    mode: min
    min_delta: 0
    patience: 2
  GradientAccumulationScheduler:
    scheduling: {0: 10}
  StochasticWeightAveraging:
    swa_lrs: 1.0e-2
    swa_epoch_start: 10
    annealing_epochs: 5
    annealing_strategy: cos
logger:
  name: WandbLogger
  save_dir: local
