project: Recommending
name: "PMF movielens sweep"
method: random
metric:
  goal: maximize
  name: test_ndcg@100.mean
parameters:
  model:
    name:
      values:
        - ProbabilityMatrixFactorization
        - ConstrainedProbabilityMatrixFactorization
    latent_dimension:
      min: 10
      max: 300
    weight_decay:
      values:
        - 1.0e-4
        - 1.0e-3
        - 1.0e-2
  loss:
    name:
      values:
        - MSELoss
        - ImplicitAwareSparseLoss
        - PersonalizedRankingLoss
  datamodule:
    directory: local/ml-100k
    num_workers: 4
  lightning_module:
    name: MovieLensBaselineRecommender
  optimizer:
    name: Adam
  logger:
    name: WandbLogger
    save_dir: local
  trainer:
    max_epochs: 50
    accelerator: gpu
    devices: [5]
    default_root_dir: local
    check_val_every_n_epoch: 5
    amp_backend: native
  callbacks:
    WandbWatcher:
      log_every_n_steps: 50
    EarlyStopping:
      monitor: val_loss
      mode: min
      patience: 5
#    GradientAccumulationScheduler:
#      scheduling: "{0: 10}"
#    StochasticWeightAveraging:
#      swa_lrs:
#        min: 1.0e-3
#        max: 1.0e-2
#      swa_epoch_start:
#        min: 10
#        max: 15
#      annealing_epochs: 5
#      annealing_strategy: cos
