project: Recommending
name: "PMF sweep level"
method: bayes
metric:
  goal: minimize
  name: val_loss
parameters:
  model:
    name: ProbabilityMatrixFactorization
    latent_dimension:
      min: 10
      max: 20
    weight_decay:
      min: 1.0e-3
      max: 1.0e-2
  lightning_module:
    name: LitProbabilityMatrixFactorization
    batch_size: 1.0e+8
    num_workers: 4
  optimizer:
    name: SGD
    lr:
      min: 5.0e-4
      max: 5.0e-3
    momentum:
      min: 0.9
      max: 0.99
  trainer:
    max_epochs: 50
    accelerator: gpu
    default_root_dir: local
    check_val_every_n_epoch: 3
    amp_backend: native
  callbacks:
    EarlyStopping:
      monitor: val_loss
      mode: min
      min_delta: 1.0e-2
      patience: 2
    GradientAccumulationScheduler:
      scheduling: "{0: 10}"
    StochasticWeightAveraging:
      swa_lrs:
        min: 1.0e-3
        max: 1.0e-2
      swa_epoch_start:
        min: 10
        max: 15
      annealing_epochs: 5
      annealing_strategy: cos
  logger:
    name: WandbLogger
    save_dir: local
sweep_id: 0nf7i2wq
