project: Recommending
name: "PMF movielens sweep"
method: random
metric:
  goal: maximize
  name: test_ndcg@100.mean
parameters:
  model:
    name: SLIM
    l2_coefficient: 1.0e-4
    l1_coefficient: 1.0e-4
  loss:
    name:
      values:
        - MSELoss
        - ImplicitAwareSparseLoss
        - PersonalizedRankingLoss
  datamodule:
    directory: local/ml-100k
    num_workers: 4
  lightning_module:
    name: MovieLensSLIMRecommender
  optimizer:
    name: Adam
  logger:
    name: WandbLogger
    save_dir: local
  trainer:
    accelerator: gpu
    devices: [4]
    reload_dataloaders_every_n_epochs: 1
    accumulate_grad_batches: 1
    enable_model_summary: false
    limit_val_batches: 0
    log_every_n_steps: 1
    default_root_dir: local
    num_sanity_val_steps: 0
    max_epochs: -1
  callbacks:
    WandbWatcher:
      log_every_n_steps: 50
    EarlyStopping:
      monitor: val_loss
      mode: min
      patience: 5
