project: Recommending
name: "SLIM movielens sweep 4"
method: random
metric:
  goal: maximize
  name: test_ndcg@100.mean
parameters:
  model:
    name: SLIM
    l2_coefficient:
      values:
        - 1.0e-5
        - 1.0e-4
        - 1.0e-3
    l1_coefficient:
      values:
        - 1.0e-7
        - 1.0e-6
        - 1.0e-5
  loss:
    name: MSELoss
  datamodule:
    directory: local/ml-100k
    num_workers: 4
  lightning_module:
    name: MovieLensSLIMRecommender
    patience: 3
    min_delta:
      values:
        - 1.0e-6
        - 1.0e-5
        - 1.0e-4
  optimizer:
    name: Adam
  logger:
    name: WandbLogger
    save_dir: local
  trainer:
    accelerator: gpu
    devices: [4]
    reload_dataloaders_every_n_epochs: 1
    accumulate_grad_batches: 1
    enable_model_summary: false
    limit_val_batches: 0
    log_every_n_steps: 1
    default_root_dir: local
    num_sanity_val_steps: 0
    max_epochs: -1
