project: Recommending
name: "SLIM debug run"
model:
  name: SLIM
  l2_coefficient: 1.0
  l1_coefficient: 1.0
loss:
  name: PersonalizedRankingLoss
  max_rating: 5
datamodule:
  name: SLIMDataModule
  directory: local/ml-100k
  batch_size: 100
  num_workers: 0
callbacks:
  SLIMRecommendingIMDBCallback:
    path_to_imdb_ratings_csv: "local/my_imdb_ratings.csv"
    path_to_movielens_folder: "local/ml-100k"
    k: 10
  SLIMRecommendingMetricsCallback:
    directory: "local/ml-100k"
    k: [10, 20]
lightning_module:
  name: LitSLIM
optimizer:
  name: Adam
trainer:
  reload_dataloaders_every_n_epochs: 1
  accumulate_grad_batches: 1
  enable_model_summary: false
  val_check_interval: 10
  log_every_n_steps: 1
  default_root_dir: local
  num_sanity_val_steps: 0
  max_epochs: -1
logger:
  name: WandbLogger
  save_dir: local
