project: Recommending
name: "SLIM debug run"
stage: test
model:
  name: SLIM
  l2_coefficient:
    values:
      - 1.0e-5
      - 1.0e-4
      - 1.0e-3
      - 1.0e-2
  l1_coefficient:
    values:
      - 1.0e-5
      - 1.0e-4
      - 1.0e-3
      - 1.0e-2
loss:
  name:
    values:
      - MSELoss
      - ImplicitAwareSparseLoss
      - PersonalizedRankingLoss
datamodule:
  directory: local/ml-100k
  batch_size: 100
  num_workers: 4
lightning_module:
  name: MovieLensSLIMRecommender
optimizer:
  name: Adam
trainer:
  accelerator: gpu
  devices: [2]
  reload_dataloaders_every_n_epochs: 1
  accumulate_grad_batches: 1
  enable_model_summary: false
  limit_val_batches: 0
  log_every_n_steps: 1
  default_root_dir: local
  num_sanity_val_steps: 0
  max_epochs: -1
logger:
  name: WandbLogger
  save_dir: local
