project: Recommending
name: "Baseline basic"
method: random
metric:
  goal: maximize
  name: test_ndcg@10.mean
parameters:
  model:
    class_name:
      values: [RandomRecommender, PopularRecommender]
  lightning_module:
    class_name: MovieLensNonGradientRecommender
  trainer:
    num_sanity_val_steps: 0

