project: Recommending
name: "MF"
method: random
metric:
  goal: maximize
  name: test_ndcg@10.mean
parameters:
  model:
    class_name: MatrixFactorization
    latent_dimension: 150
    weight_decay: 1.0e-4
  loss:
    class_name: MSEConfidenceLoss
    confidence:
      distribution: uniform
      min: 0.9
      max: 1.0
  datamodule:
    num_workers: 4
  lightning_module:
    class_name: MovieLensMFRecommender
  optimizer:
    class_name: Adam
  trainer:
    max_epochs: 50
    accelerator: gpu
    devices: [5]
    default_root_dir: local
    check_val_every_n_epoch: 1
    amp_backend: native
  callbacks:
    EarlyStopping:
      monitor: val_loss
      mode: min
      patience: 5
